version: 2
groups:
  code-review:
    approve_by_comment:
      approve_regex: '(?i):shipit:|:\\+1:|LGTM|Approved'
      enabled: true
      reject_regex: ^Rejected
    required: 1
    reset_on_push:
      enabled: false
    users:
    - czerny92
    - jurampark
    - kmmin
    - KyuaKwon
    - ttochi
    - persona0220
    
